<a href="https://colab.research.google.com/github/maskot1977/Python2020/blob/1028/56.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!date

Wed Oct 28 06:07:48 UTC 2020


In [3]:
import numpy as np

a = np.array([
              [1, 2], 
              [1, -3]
              ])
b = np.array([
              [1, 2], 
              [2, 5]
              ])

In [4]:
a + b

array([[2, 4],
       [3, 2]])

In [5]:
a - b

array([[ 0,  0],
       [-1, -8]])

In [6]:
a@b

array([[  5,  12],
       [ -5, -13]])

In [7]:
a.dot(b)

array([[  5,  12],
       [ -5, -13]])

In [8]:
b@a

array([[  3,  -4],
       [  7, -11]])

In [9]:
b.dot(a)

array([[  3,  -4],
       [  7, -11]])

In [10]:
np.linalg.inv(b)

array([[ 5., -2.],
       [-2.,  1.]])

In [11]:
a@np.linalg.inv(b)

array([[ 1.,  0.],
       [11., -5.]])

In [12]:
a.dot(np.linalg.inv(b))

array([[ 1.,  0.],
       [11., -5.]])

In [14]:
c = np.array([
              [1, -1, -1], 
              [-1, 2, 2], 
              [2, 1, 2]
              ])

In [15]:
np.linalg.inv(c)

array([[ 2.00000000e+00,  1.00000000e+00, -3.33066907e-16],
       [ 6.00000000e+00,  4.00000000e+00, -1.00000000e+00],
       [-5.00000000e+00, -3.00000000e+00,  1.00000000e+00]])

In [18]:
w, v = np.linalg.eig(a)
print("固有値", w)
print("固有ベクトル", v)

固有値 [ 1.44948974 -3.44948974]
固有ベクトル [[ 0.97566304 -0.40997761]
 [ 0.21927526  0.91209559]]


In [19]:
w, v = np.linalg.eig(b)
print("固有値", w)
print("固有ベクトル", v)

固有値 [0.17157288 5.82842712]
固有ベクトル [[-0.92387953 -0.38268343]
 [ 0.38268343 -0.92387953]]


In [20]:
w, v = np.linalg.eig(c)
print("固有値", w)
print("固有ベクトル", v)

固有値 [0.16071324+0.j         2.41964338+0.60629073j 2.41964338-0.60629073j]
固有ベクトル [[-0.18175202+0.j         -0.50539199+0.0305654j  -0.50539199-0.0305654j ]
 [-0.76740476+0.j          0.81723109+0.j          0.81723109-0.j        ]
 [ 0.61486269+0.j         -0.08122319+0.26302251j -0.08122319-0.26302251j]]


In [21]:
!date

Wed Oct 28 06:14:26 UTC 2020
